import { formatTimestamp } from '../dates/format';
import { applyDataset, parseSchema, readPreferences, storageKey } from './rules';

/**
 * The pre-paint bootstrap: apply the saved reading preferences and rewrite dates while the
 * document is still parsing, so nothing flashes and no date column starts out empty. It is the
 * only script that blocks rendering, which is why it does nothing else. The rules come from
 * `#aggr-preferences`, generated by src/config/preferences.rs, and the values from storage.
 */
export function bootstrap(doc: Document, get: (key: string) => string | null, now: () => number = Date.now): void {
  const schema = parseSchema(doc.getElementById('aggr-preferences')?.textContent);
  const values = readPreferences(schema, (key) => get(storageKey(key)));
  applyDataset(schema, values, doc.documentElement);
  watchDates(doc, String(values['date-format'] ?? 'relative'), now);
}

/**
 * One `<time>` as the app will render it: the text in the preferred style and the accessible
 * name made of that text and the exact tooltip, which stays where the template put it (on the
 * `[data-date-tooltip]` label or on the element itself). A duration or an empty element is
 * left alone.
 */
export function rewriteDate(time: Element, style: string, now: number): void {
  if (!time.textContent) return;
  const text = formatTimestamp(Date.parse(time.getAttribute('datetime') || ''), style, now);
  if (text === null) return;
  const tooltip = (time.closest('[data-date-tooltip]') ?? time).getAttribute('title');
  if (tooltip) time.setAttribute('aria-label', `${text}; ${tooltip}`);
  if (time.textContent !== text) time.textContent = text;
}

export function rewriteDates(root: ParentNode, style: string, now: number): void {
  for (const time of root.querySelectorAll('time[datetime]')) rewriteDate(time, style, now);
}

/**
 * Rewrite every date in the document, and while it is still parsing, each one as it appears
 * rather than at the end: a reader should never see a raw timestamp replaced under them.
 */
export function watchDates(doc: Document, style: string, now: () => number): void {
  if (doc.readyState === 'loading') {
    const changed = (records: MutationRecord[]) => {
      const times = new Set<Element>();
      const collect = (node: Node, descendants: boolean) => {
        const element = node.nodeType === Node.ELEMENT_NODE ? (node as Element) : node.parentElement;
        if (!element) return;
        const time = element.closest('time[datetime]');
        if (time) times.add(time);
        if (descendants && element === node) for (const found of element.querySelectorAll('time[datetime]')) times.add(found);
      };
      for (const record of records) {
        collect(record.target, false);
        for (const node of record.addedNodes) collect(node, true);
      }
      const at = now();
      for (const time of times) rewriteDate(time, style, at);
    };
    const observer = new MutationObserver(changed);
    observer.observe(doc.documentElement, { childList: true, subtree: true, characterData: true });
    doc.addEventListener(
      'DOMContentLoaded',
      () => {
        changed(observer.takeRecords());
        observer.disconnect();
        rewriteDates(doc, style, now());
      },
      { once: true },
    );
  }
  rewriteDates(doc, style, now());
}
