identity = "fc46a9cbbce375a2ba691f0ff90c53010d405b80"
resolved_url = "https://github.blog/changelog/feed/"
title = "Archive: 2026 - GitHub Changelog"
site_url = "https://github.blog/changelog/"
language = "en-US"
etag = 'W/"bb5249c75837be11c4631c1fa716e825"'
last_modified = "Wed, 30 Sep 2026 17:37:48 GMT"
body_hash = "ba64b9849dec97c7d6d05d250fe9de1b0faae2b0"
