identity = "5a8d48733165db8e1d6a29713425654ee12968d8"
resolved_url = "https://lobste.rs/rss"
title = "Lobsters"
site_url = "https://lobste.rs/"
etag = '"dlsuf6c7egyfbx0-gzip"'
last_modified = "Wed, 30 Sep 2026 17:56:18 GMT"
body_hash = "5178fde0500b5f5deb4a119d8ee1e07a76bdd0d8"
