//! First path segments a shared platform serves itself, so they never name an account.
//!
//! Nothing here is chosen by hand. GitLab and Forgejo reserve these names in their own source; the
//! other platforms publish them as the top-level paths of their `robots.txt`. A robots.txt blocks
//! individual members too, so an entry is kept only where the platform serves its own page rather
//! than someone's profile, and each list names what was dropped for that reason. A path that a
//! platform documents as holding one piece of content, such as a Twitch video, cites that document.
//!
//! Retrieved 2026-09-27. Matching ignores ASCII case. Refresh a list from its source rather than
//! extending it: a guessed route silently turns a real publisher into its host.

/// Forgejo, which Codeberg runs: `reservedUsernames` in `models/user/user.go`
/// (<https://codeberg.org/forgejo/forgejo/src/branch/forgejo/models/user/user.go>).
pub(super) const CODEBERG: &[&str] = &[
    "-",
    ".",
    "..",
    ".well-known",
    "actor",
    "admin",
    "api",
    "assets",
    "attachments",
    "avatar",
    "avatars",
    "captcha",
    "explore",
    "favicon.ico",
    "forgejo-actions",
    "ghost",
    "gitea-actions",
    "issues",
    "login",
    "manifest.json",
    "metrics",
    "milestones",
    "notifications",
    "org",
    "pulls",
    "repo",
    "repo-avatars",
    "report_abuse",
    "robots.txt",
    "sitemap.xml",
    "ssh_info",
    "swagger.v1.json",
    "user",
    "v2",
];

/// <https://github.com/robots.txt>, without `account-login`, `Explodingstuff` and `ekansa`, which
/// serve members' profiles. GitHub publishes no list of its own, so a route missing from its
/// robots.txt still reads as an account.
pub(super) const GITHUB: &[&str] = &[
    ".git",
    "about",
    "copilot",
    "customer-stories",
    "enterprise",
    "features",
    "gist",
    "marketplace",
    "mcp",
    "newsroom",
    "pricing",
    "resources",
    "search",
    "security",
    "solutions",
];

/// GitLab's `TOP_LEVEL_ROUTES` in `lib/gitlab/path_regex.rb`, which its documentation names as the
/// words "reserved as usernames or top-level groups"
/// (<https://docs.gitlab.com/user/reserved_names/>).
pub(super) const GITLAB: &[&str] = &[
    "-",
    ".well-known",
    "404.html",
    "422.html",
    "500.html",
    "502.html",
    "503.html",
    "admin",
    "api",
    "apple-touch-icon.png",
    "assets",
    "dashboard",
    "deploy.html",
    "explore",
    "favicon.ico",
    "favicon.png",
    "groups",
    "health_check",
    "help",
    "import",
    "jwt",
    "login",
    "o",
    "oauth",
    "profile",
    "projects",
    "public",
    "robots.txt",
    "s",
    "search",
    "sitemap",
    "sitemap.xml",
    "sitemap.xml.gz",
    "slash-command-logo.png",
    "snippets",
    "unsubscribes",
    "uploads",
    "users",
    "v2",
];

/// <https://medium.com/robots.txt>.
pub(super) const MEDIUM: &[&str] = &[
    "@me",
    "_",
    "about",
    "business",
    "earn",
    "gift",
    "m",
    "me",
    "media",
    "membership",
    "p",
    "partner-program",
    "r",
    "search",
    "trending",
    "verified-authors",
];

/// <https://soundcloud.com/robots.txt>.
pub(super) const SOUNDCLOUD: &[&str] = &[
    "accessibility-statement",
    "community-guidelines",
    "company",
    "discover",
    "download",
    "getstarted",
    "go",
    "imprint",
    "jobs",
    "messages",
    "pro",
    "search",
    "settings",
    "sitemap",
    "sitemapindex",
    "stories",
    "stream",
    "terms-of-use",
    "topic",
    "transparency-reports",
    "upload",
    "you",
];

/// <https://www.twitch.tv/robots.txt>, plus `videos`: Twitch's API reference gives a video's URL as
/// `https://www.twitch.tv/videos/335921245` (Get Videos, <https://dev.twitch.tv/docs/api/reference/>).
pub(super) const TWITCH: &[&str] = &[
    ".well-known",
    "activate",
    "admin",
    "auth",
    "beta",
    "bits-checkout",
    "chat",
    "claim",
    "collab",
    "copyright-claims",
    "directory",
    "dj-signup",
    "download-keys",
    "drops",
    "email-unsubscribe",
    "embed",
    "extensions",
    "gl",
    "guest-star",
    "inventory",
    "login",
    "message",
    "moderator",
    "oss-attribution",
    "payments",
    "popout",
    "r",
    "redeem",
    "report-appeal",
    "search",
    "settings",
    "signup",
    "sportradar-widgets",
    "sq",
    "stale",
    "stream",
    "subscriptions",
    "user",
    "videos",
    "wallet",
    "wv",
];

/// <https://vimeo.com/robots.txt>, without `flarepoint`, a member's profile, and `ablincoln`, which
/// serves nothing; plus `album`, `channels`, `event`, `groups` and `ondemand`, the containers of a
/// video in the URL schemes Vimeo registers for oEmbed (<https://oembed.com/providers.json>).
pub(super) const VIMEO: &[&str] = &[
    "_",
    "_global_notifications",
    "_next",
    "_rv",
    "about",
    "album",
    "api",
    "blog",
    "campaigns",
    "channels",
    "couchmode",
    "create",
    "customers",
    "de",
    "download",
    "enterprise",
    "es",
    "event",
    "events",
    "features",
    "forgot_password",
    "fr",
    "groups",
    "help",
    "integrations",
    "jp",
    "ko",
    "legal",
    "manage",
    "musicstore",
    "ondemand",
    "ott",
    "product",
    "pt-br",
    "reviews",
    "search",
    "solutions",
    "store",
    "upgrade-plan",
    "user",
    "video-uploader",
    "vimeo-academy",
];

/// <https://x.com/robots.txt>.
pub(super) const X: &[&str] = &["account", "hashtag", "i", "search", "settings"];
